plugins {
    id 'org.moddingx.modgradle.meta' version '5.1.5'
}

repositories {
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev/"
    }
    maven {
        name = "MelanX"
        url = "https://maven.melanx.de"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = "Twilight Forest"
        url = "https://maven.tamaized.com/releases"
    }
}

var dev = System.getenv('IS_DEV')?.toBoolean() ?: false
var baseVersion = '21.1'
var libxVersion = '1.21.1-6.0.15'
var jeiVersion = '19.21.0.247'
var morevanillalibVersion = '21.1.4'
var morevanillatoolsVersion = '21.1.2'
var simplestcoppergearVersion = '1.0.7'
var aetherVersion = '1.21.1-1.5.8-neoforge'
var deepaetherVersion = '1.21.1-1.1.5'
var aetherlostcontentVersion = 'no 1.21 version yet' // todo
var twilightForestVersion = '4.7.3196'
var owoVersion = '0.12.15.1-beta.3+1.21'
var structuregelapiVersion = 'dependency of aether lost content, not required yet' // todo

mod.configure {
    modid 'vanillaaiots'
    group 'de.melanx'
    versioning {
        if (dev) {
            def gitCommitHash = ['git', 'rev-parse', 'HEAD'].execute().text.trim()
            constant baseVersion + (gitCommitHash ? "-${gitCommitHash}" : '')
        } else {
            base baseVersion
            maven 'https://maven.melanx.de/release'
        }
    }

    neoforge project.hasProperty('neo_version') ? project.neo_version : "${baseVersion}.118"

    license 'The Apache License, Version 2.0'
    github 'ChaoticTrials/VanillaAIOTs'

    artifacts {
        sources {
            publishToRepositories()
        }
    }

    changelog {
        def lines = defaultChangelog.toString().split('\n')
        def filteredChangelog = lines.findAll { !it.startsWith('- [[meta]') }.join('\n')

        return filteredChangelog
    }


    publishing {
        maven {
            name 'melanx'
            url 'https://maven.melanx.de/release'
            credentials(PasswordCredentials)
        }
    }

    upload {
        all {
            type 'release'
            environmentType 'client_and_server'
            require 'libx'
            optional 'morevanillalib'
            optional 'morevanillatools'
            optional 'simplest-copper-gear'
            optional 'aether'
            optional 'deep-aether'
        }
        curseforge {
            projectId 482123
            optional 'the-twilight-forest'
        }
        modrinth {
            projectId 'WN2YCymY'
        }
    }
}

dependencies {
    annotationProcessor "org.moddingx:LibX:${libxVersion}"

    implementation "org.moddingx:LibX:${libxVersion}"
    implementation "de.melanx:MoreVanillaLib:${morevanillalibVersion}"
    implementation "de.melanx:MoreVanillaTools:${morevanillatoolsVersion}"
    implementation "mezz.jei:jei-1.${baseVersion}-neoforge:${jeiVersion}"

    implementation "maven.modrinth:simplest-copper-gear:${simplestcoppergearVersion}"
    implementation "maven.modrinth:aether:${aetherVersion}"
    implementation "maven.modrinth:deep-aether:${deepaetherVersion}"
//    implementation "maven.modrinth:aether-lost-content:${aetherlostcontentVersion}"

    implementation "team-twilight:twilightforest:${twilightForestVersion}:universal"

    implementation "maven.modrinth:owo-lib:${owoVersion}"
//    runtimeOnly "maven.modrinth:structure-gel-api:${structuregelapiVersion}"
}
