modLoader="javafml"
loaderVersion="[40,)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/VanillaAIOTs/issues"

[[mods]]
modId="vanillaaiots"
version="${file.jarVersion}"
displayName="Vanilla AIOTs"
updateJSONURL="https://assets.melanx.de/updates/vanilla-aiots.json"
authors="MelanX"
description="""
Adds a ton of new AIOTs to the game! AIOT stands for \"All In One Tool\".
"""

[[dependencies.vanillaaiots]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.68,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaaiots]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.2-3.2.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.vanillaaiots]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaaiots]]
    modId="morevanillatools"
    mandatory=false
    versionRange="[1.18.2-4.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaaiots]]
    modId="morevanillalib"
    mandatory=false
    versionRange="[1.18.2-3.1.0,)"
    ordering="NONE"
    side="BOTH"
