modLoader="javafml"
loaderVersion="[${fml},)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/VanillaAIOTs/issues"

[[mods]]
modId="vanillaaiots"
version="${version}"
displayName="Vanilla AIOTs"
updateJSONURL="https://assets.melanx.de/updates/vanilla-aiots.json"
authors="MelanX"
description="""
Adds a ton of new AIOTs to the game! AIOT stands for \"All In One Tool\".
"""

[[dependencies.vanillaaiots]]
    modId="forge"
    mandatory=true
    versionRange="[${forge},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaaiots]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaaiots]]
    modId="libx"
    mandatory=true
    versionRange="[1.20.1-5.0.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.vanillaaiots]]
    modId="morevanillatools"
    mandatory=false
    versionRange="[1.20.1-6.0.0,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.vanillaaiots]]
    modId="morevanillalib"
    mandatory=false
    versionRange="[1.20.1-5.0.1,)"
    ordering="NONE"
    side="BOTH"
