modLoader="javafml"
loaderVersion="[41,)"
license="The Apache License, Version 2.0"
issueTrackerURL="https://github.com/MelanX/VanillaAIOTs/issues"

[[mods]]
modId="vanillaaiots"
version="${file.jarVersion}"
displayName="Vanilla AIOTs"
updateJSONURL="https://assets.melanx.de/updates/vanilla-aiots.json"
authors="MelanX"
description="""
Adds a ton of new AIOTs to the game! AIOT stands for \"All In One Tool\".
"""

[[dependencies.vanillaaiots]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.98,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaaiots]]
    modId="libx"
    mandatory=true
    versionRange="[1.19-4.0.7,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.vanillaaiots]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19, 1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaaiots]]
    modId="morevanillatools"
    mandatory=false
    versionRange="[1.19-5.0.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillaaiots]]
    modId="morevanillalib"
    mandatory=false
    versionRange="[1.19-4.0.1,)"
    ordering="NONE"
    side="BOTH"
